# Generated by Django 6.0.3 on 2026-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoestudo',
            name='tipo',
            field=models.CharField(choices=[('exercicio', 'Exercício'), ('revisao', 'Revisão'), ('simulado', 'Simulado'), ('pratica', 'Prática'), ('leitura', 'Leitura')], default='exercicio', max_length=20),
        ),
    ]
