# Generated by Django 6.0.3 on 2026-03-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_alter_cronograma_id_alter_disciplina_id_and_more'),
        ('cronograma', '0002_sessaoestudo_tipo'),
    ]

    operations = [
    ]
