# Generated by Django 6.0.3 on 2026-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0003_merge_20260328_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
