# Generated by Django 5.2.12 on 2026-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0004_alter_cronograma_id_alter_disciplina_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoestudo',
            name='prioritaria',
            field=models.BooleanField(default=False),
        ),
    ]
