# Generated by Django 6.0.3 on 2026-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0005_sessaoestudo_prioritaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoestudo',
            name='prioritaria',
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=10, null=True),
        ),
    ]
