# Generated by Django 6.0.3 on 2026-03-27 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Matéria')),
                ('icone', models.CharField(choices=[('📐', 'Matemática'), ('📖', 'Português'), ('🔬', 'Ciências'), ('🌍', 'Geografia'), ('📜', 'História'), ('⚗️', 'Química'), ('⚡', 'Física'), ('🌿', 'Biologia'), ('🗣️', 'Inglês'), ('🎨', 'Artes'), ('📚', 'Outro')], default='📚', max_length=10, verbose_name='Ícone')),
                ('cor', models.CharField(default='#7f8fdc', help_text='Ex: #7f8fdc', max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoDeEstudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, verbose_name='Duração (segundos)')),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciada em')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='sessaodeestudos.materia', verbose_name='Matéria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_estudo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Estudos',
                'verbose_name_plural': 'Sessões de Estudos',
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
