# Generated by Django 5.2.12 on 2026-04-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessaodeestudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do assunto')),
                ('resumo', models.TextField(help_text='Resumo do assunto exibido na aba de flashcards.', verbose_name='Resumo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='sessaodeestudos.materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.TextField(help_text='Pergunta, conceito ou termo exibido na frente do card.', verbose_name='Frente (pergunta/conceito)')),
                ('verso', models.TextField(help_text='Resposta ou explicação detalhada exibida no verso.', verbose_name='Verso (resposta/explicação)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['ordem'],
            },
        ),
    ]
