# Generated by Django 6.0.3 on 2026-04-22 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_usuarios_que_estudaram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='usuarios_que_estudaram',
            field=models.ManyToManyField(blank=True, related_name='flashcards_estudados', to=settings.AUTH_USER_MODEL),
        ),
    ]
