# Generated by Django 6.0.3 on 2026-05-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assuntos_recorrentes', '0001_initial'),
    ]

    operations = [
    ]
