# Generated by Django 5.2.12 on 2026-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('edicao', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('area_conhecimento', models.CharField(max_length=50)),
                ('total_questoes', models.PositiveIntegerField()),
                ('pdf_prova', models.FileField(blank=True, null=True, upload_to='provas_pdf/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['-ano', 'edicao'],
            },
        ),
    ]
