# Generated by Django 6.0.3 on 2026-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas_antigas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='pdf_prova',
        ),
        migrations.AddField(
            model_name='prova',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
